### ISSUE TITLE
test

### ISSUE THREAD

**Issue by 07NS** [js313/todo#1]
process.env.MONGODB_URL refers to undefine
file global.d.ts:
```
    interface Dict<T> {
        [key: string]: T | undefined;
    }
```

**Comment by js313** [comment]
You need to setup the project on your system first, I will add a Readme showing the instructions as soon as I can.

**Comment by 07NS** [comment]
I have downloaded nodejs and express and mongoose.Should I also download dotenv?

**Comment by 07NS** [comment]
I will just look at your instructions and that will probably fix it. Can you add readme file now?

**Comment by js313** [comment]
@07NS Instructions in readme added.
